# Generated by Django 5.2 on 2025-04-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('emotion', models.CharField(blank=True, max_length=255)),
                ('episode', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
