# Generated by Django 5.2 on 2025-05-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twimood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='episode',
        ),
        migrations.AddField(
            model_name='tweet',
            name='labels',
            field=models.TextField(blank=True, default=''),
        ),
    ]
